### ISSUE TITLE
Want less expensive alternative to coap_get_code() to determine if Empty

### ISSUE THREAD

**Issue by kb2ma** [kaspar030/sock#19]
`coap_get_code()` includes a multiplication, addition and a some accesses. However, sometimes a client only wants to know if the code is 0.00 for an Empty message. @kaspar030 and I suggest addition of a coap_is_empty() and/or coap_get_code_raw().

**Comment by kaspar030** [comment]
Like a helper that returns ```pkt->hdr->code``` or ```pkt->hdr->code == 0```? Sure, why not.

**Comment by kaspar030** [comment]
Closed by #20.
